ROCANA-9215: Rename and change package of Lucene forked code
scalingdata/rocana-lucene-codec pull request #6
Opened 2017-01-25 20:58 UTC by bradcupit

2017-01-25 22:02 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaBlockTreeTermsReader.java
> + *     for performance.
Maybe add: "for performance improvements and on HDFS this is a redundant check to the checksumming of blocks already done by HDFS".

2017-01-26 01:06 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaBlockTreeTermsReader.java
> + * is the original file from Lucene).
should add the version and/or Lucene tag to this comment: 5.5.0, git tag `releases/lucene-solr/5.5.0`

2017-01-26 01:07 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaBlockTreeTermsReader.java
> + * See ROCANA-8229.
This JIRA is not publicly visible but this codec is open sourced, so shouldn't refer to it here, but rather describe the information here.

2017-01-26 01:09 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaBlockTreeTermsReader.java
> + * Fork of Lucene's {@link com.rocana.lucene.codec.v1.RocanaBlockTreeTermsReader}.
This reference is wrong - should point to Lucene's package/class.

2017-01-26 01:11 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaBlockTreeTermsReader.java
> +                                          new RocanaFieldReader(this, fieldInfo, numTerms, rootCode, sumTotalTermFreq, sumDocFreq, docCount,
The spacing formatting doesn't conform to Rocana standards. Do we apply those standards to open sourced code? (I vote yes.)

2017-01-26 01:13 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaFieldReader.java
> + * Fork of Lucene's {@link com.rocana.lucene.codec.v1.RocanaFieldReader}.
Wrong reference - should point to Lucene's package/class.

2017-01-26 01:13 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaFieldReader.java
> + * See ROCANA-8229
Same comment here about referring to internal only JIRA tickets in open sourced code.

2017-01-26 01:14 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaIntersectTermsEnum.java
> + * @see RocanaSearchCodecV1
Same comment here about referring to internal only JIRA tickets in open sourced code.

2017-01-26 01:14 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaIntersectTermsEnumFrame.java
> + * See ROCANA-8229
Same comment here about referring to internal only JIRA tickets in open sourced code.

2017-01-26 01:15 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaLucene50PostingsFormat.java
> + * See ROCANA-8229.
Same comment here about referring to internal only JIRA tickets in open sourced code.

2017-01-26 01:15 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaLucene50PostingsFormat.java
> + * Fork of Lucene's {@link com.rocana.lucene.codec.v1.RocanaLucene50PostingsFormat}.
wrong reference

2017-01-26 01:16 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaSegmentTermsEnum.java
> + * See ROCANA-8229
Same comment here about referring to internal only JIRA tickets in open sourced code.

2017-01-26 01:16 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaSegmentTermsEnumFrame.java
> + * See ROCANA-8229
Same comment here about referring to internal only JIRA tickets in open sourced code.

2017-01-26 01:17 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaStats.java
> + * Fork of Lucene's {@link com.rocana.lucene.codec.v1.RocanaStats}.
wrong reference

2017-01-26 01:17 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaStats.java
> + * See ROCANA-8229
Same comment here about referring to internal only JIRA tickets in open sourced code.

2017-01-26 01:17 UTC, mpeterson0x0 commented on src/test/java/com/rocana/lucene/codec/v1/TestBlockPostingsFormat.java
> + * Fork of Lucene's {@link com.rocana.lucene.codec.v1.TestBlockPostingsFormat}.
wrong reference

2017-01-26 01:17 UTC, mpeterson0x0 commented on src/test/java/com/rocana/lucene/codec/v1/TestBlockPostingsFormat.java
> + * See ROCANA-8229
Same comment here about referring to internal only JIRA tickets in open sourced code.

2017-01-26 01:18 UTC, mpeterson0x0 commented on src/test/java/com/rocana/lucene/codec/v1/TestBlockPostingsFormat2.java
> + * Fork of Lucene's {@link com.rocana.lucene.codec.v1.TestBlockPostingsFormat2}.
wrong reference

2017-01-26 01:18 UTC, mpeterson0x0 commented on src/test/java/com/rocana/lucene/codec/v1/TestBlockPostingsFormat2.java
> + * See ROCANA-8229
Same comment here about referring to internal only JIRA tickets in open sourced code.

2017-01-26 01:18 UTC, mpeterson0x0 commented on src/test/java/com/rocana/lucene/codec/v1/TestBlockPostingsFormat3.java
> + * Fork of Lucene's {@link com.rocana.lucene.codec.v1.TestBlockPostingsFormat3}.
wrong reference

2017-01-26 01:18 UTC, mpeterson0x0 commented on src/test/java/com/rocana/lucene/codec/v1/TestBlockPostingsFormat3.java
> + * See ROCANA-8229
Same comment here about referring to internal only JIRA tickets in open sourced code.

2017-01-26 01:21 UTC, mpeterson0x0 commented
Overall comment: how do we know that you caught all the references and properly renamed them? One way: check all the import statements (either manually or write a script) to make sure none of the forked classes are referenced in the forked classes or anywhere else in the Rocana codebase - should we add that as an acceptance criterion for this ticket?

2017-01-26 01:22 UTC, mpeterson0x0 requested changes
Finished round 1 review. Minor javadoc changes requested and then one overall sanity check (see overall comment) requested.

2017-01-26 15:33 UTC, bradcupit commented on src/main/java/com/rocana/lucene/codec/v1/RocanaBlockTreeTermsReader.java
> +                                          new RocanaFieldReader(this, fieldInfo, numTerms, rootCode, sumTotalTermFreq, sumDocFreq, docCount,
We're an extremely minor fork of Lucene, ultimately just trying to comment out one line of code.

Ideally we'd stay as close to the Lucene code as possible so we can diff to see **exactly** what changed in our fork. I've used this style before and it's very nice. Even if we never use it we have a scientific way of determining exactly what we changed, no matter how much or little we diverge in the future. We could also generate a patch from this diff, to apply onto a newer version of Lucene. I'm not recommending we do that, just saying it's possible.

I vote we don't adhere to Rocana's standard as that would muddy the diff.

2017-01-26 15:41 UTC, bradcupit commented on src/main/java/com/rocana/lucene/codec/v1/RocanaBlockTreeTermsReader.java
> + * See ROCANA-8229.
I'll remove it from all the forked files. For the benefit of the Rocana engineer (and let's be honest, there's a 90% chance this code's only ever be used by Rocana engineers) I'll keep the reference in the main RocanaSearchCodecV1 javadocs, and say what we have in the README.md:

> If you have access to Rocana's JIRA, see ROCANA-8229.

2017-01-26 15:54 UTC, bradcupit commented on src/main/java/com/rocana/lucene/codec/v1/RocanaBlockTreeTermsReader.java
> + *     for performance.
changed the wording

2017-01-26 15:54 UTC, bradcupit commented on src/main/java/com/rocana/lucene/codec/v1/RocanaBlockTreeTermsReader.java
> + * is the original file from Lucene).
done, but at the top of the javadocs instead

2017-01-26 15:55 UTC, bradcupit commented on src/main/java/com/rocana/lucene/codec/v1/RocanaBlockTreeTermsReader.java
> + * Fork of Lucene's {@link com.rocana.lucene.codec.v1.RocanaBlockTreeTermsReader}.
nice catch! Eclipse did this and apparently I fixed some but not all

2017-01-26 16:19 UTC, bradcupit commented
Regarding the overall comment:
>  how do we know that you caught all the references and properly renamed them?

Fair question.

Eclipse renamed them and renamed them in the files. That's why so many of the javadoc references were wrong (the ones that were correct I fixed manually). Also, the below forked classes are package private. Since we're in a different package we'd get a compile error if we accidentally referenced these:
* IntersectTermsEnum
* IntersectTermsEnumFrame
* SegmentTermsEnum
* SegmentTermsEnumFrame

I verified we don't use any of the files using a regular expression. For example:
```[^a]BlockTreeTermsReader```
That finds any reference that's not Rocan**aBlockTreeTermsReader**. In this case it found two hits: one in the javadocs where I reference the original Lucene file name, and a comment in another file.

I fixed the comments just in case we ever uncomment that code.

I repeated this process for each file and there are no violations other than these two intentional ones:
* In TestBlockPostingsFormat.testFinalBlock() line 72 returns a FieldReader, not a RocanaFieldReader
* In the same test method since we're using FieldReader.getStats() we'll get a Stats, not RocanaStats.

2017-01-26 17:37 UTC, mpeterson0x0 commented on src/main/java/com/rocana/lucene/codec/v1/RocanaBlockTreeTermsReader.java
> +                                          new RocanaFieldReader(this, fieldInfo, numTerms, rootCode, sumTotalTermFreq, sumDocFreq, docCount,
OK, we can change it later if we need to do additional changes.

2017-01-26 17:42 UTC, mpeterson0x0 approved these changes
+1

2017-01-26 19:50 UTC, merged